### ISSUE TITLE
Fix wiki main page documentation

### ISSUE THREAD

**Issue by sourabhkashyap95** [ikorennoy/jasyncfio#65]
Wiki documentation main page states
Jasyncfio similar to Java NIO API, but comes in two kinds:

**BufferedFile** - similar to Java NIO API, but asynchronous. Regular file backed by operation system page cache
DmaFile - O_DIRECT file asynchronous API

BufferedFile has been renamed to AsyncFile.

**Comment by ikorennoy** [comment]
@sourabhkashyap95, Hello! 

I appreciate your help. The page has been fixed.
