### ISSUE TITLE
EventExecutor::close-method throws NPE

### ISSUE THREAD

**Issue by JohannesLichtenberger** [ikorennoy/jasyncfio#71]
```java
    void close() {
        ring.close();
        bufRings.values().forEach(IoUringBufRing::close);
    }
```

the `bufRings` instance should in either way be initialized to an empty map instead of `null` if the condition returns false.

**Comment by ikorennoy** [comment]
Oops, I thought I had fixed it, thank you.

Please update to 0.0.6 and the problem should be gone.
