### ISSUE TITLE
Panama version

### ISSUE THREAD

**Issue by JohannesLichtenberger** [ikorennoy/jasyncfio#75]
Do you plan a version based on the FFM API (should be faster): https://youtu.be/8sFt1_7RxGk

**Comment by ikorennoy** [comment]
@JohannesLichtenberger

Yes, I will support the new API because it's faster and more important it's harder to make a mistake with it. But I'll do it no earlier than the API will be in the LTS release.

**Comment by adamretter** [comment]
So I believe that will be Java 21 LTS which has a proposed ETA of September 2023.

**Comment by ikorennoy** [comment]
@adamretter, that's right.
